fix: Invalid run unit for standard server setup

diff --git a/utils/run b/utils/run
--- a/utils/run
+++ b/utils/run
@@ -6,5 +6,10 @@
 
 for TASK in "$@"; do
 	cd "$INIT_HOME"
-	"$INIT_HOME/$TASK"
+	if [ -x "$INIT_HOME/$TASK" ]; then
+		"$INIT_HOME/$TASK"
+	else
+		echo "Invalid run unit '${TASK}'"
+		exit 1
+	fi
 done
